services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.js
    ports:
      - "59001:59001"
    volumes:
      - ./frontend:/app
    networks:
      - stained-glass-odyssey-endless-network
  backend: &backend-base
    build:
      context: ./backend
      dockerfile: ../Dockerfile.python
    ports:
      - "59002:59002"
    environment:
      AF_DB_PATH: /app/save.db
      AF_DB_KEY: ${AF_DB_KEY}
    volumes:
      - ./backend:/app
      - ${HOME}/.cache:/.cache
    networks:
      - stained-glass-odyssey-endless-network

networks:
  stained-glass-odyssey-endless-network:
    driver: bridge
