name: CI

on:
  push:
  pull_request:

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.12'
      - name: Install backend dependencies
        working-directory: backend
        run: uv sync
      - name: Run backend tests
        working-directory: backend
        run: uv run pytest

  backend-lint:
    name: Backend Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.12'
      - name: Run backend linting
        run: uvx ruff check backend

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install frontend dependencies
        working-directory: frontend
        run: bun install
      - name: Run frontend tests
        working-directory: frontend
        run: bun test

  frontend-lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install frontend dependencies
        working-directory: frontend
        run: bun install
      - name: Run frontend linting
        working-directory: frontend
        run: ESLINT_USE_FLAT_CONFIG=false bunx eslint .
