
name: Run Service Tests
on:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: self-hosted
    strategy:
      matrix:
        test_file:
          - Discord-Bot-Main/tests/test_fd_leak_monitor.py
          - Discord-Bot-Main/tests/test_ignore_user_registration.py
          - Discord-Bot-Main/tests/test_profile_export.py
          - Discord-Bot-Main/tests/test_profile_load.py
          - Discord-Bot-Main/tests/test_queue_validation.py
          - Rest-Servers/tests/test_log_rotation.py
          - Rest-Servers/tests/test_memory_exit.py
          - Rest-Servers/tests/test_profile_api_usage_validation.py
          - Rest-Servers/tests/test_profile_json_export.py
          - Rest-Servers/tests/test_profile_load_dict.py
          - Rest-Servers/tests/test_profile_v2_string_id.py
          - Rest-Servers/tests/test_status_isolation.py
          - WebUI/command-server/tests/test_codex.py
          - WebUI/command-server/tests/test_container_lifecycle.py
          - WebUI/command-server/tests/test_docker_controller.py
          - WebUI/command-server/tests/test_docx.py
          - WebUI/command-server/tests/test_logging_utils.py
          - WebUI/command-server/tests/test_prototype_apps.py
          - WebUI/command-server/tests/test_queue_endpoint.py
          - WebUI/command-server/tests/test_status_updates.py
          - WebUI/command-server/tests/test_submit_command.py
          - WebUI/command-server/tests/test_tool_queues.py
          - WebUI/command-server/tests/test_usage_string.py
          - WebUI/command-server/tests/test_voicechat.py
          - WebUI/command-server/tests/test_webinteraction.py
    steps:
      - uses: actions/checkout@v4
      - name: Install uv if not present
        run: 'command -v uv >/dev/null 2>&1 || yay -Syu --noconfirm uv'
      - name: Set up virtual environment
        run: uv venv --python python3.13
      - name: Install Discord Bot deps
        run: uv pip install -r Discord-Bot-Main/python_deps_files/master_requirements.txt
      - name: Install Rest Server packages
        run: |
          uv pip install -e ./Rest-Servers/memory
          uv pip install -e ./Rest-Servers/tools
          uv pip install -e ./Rest-Servers/tts
          uv pip install -e ./Rest-Servers/user_profiles
          uv pip install -e ./Rest-Servers/queue
          uv pip install -e ./Rest-Servers/carlyfull
      - name: Install Command Server
        run: uv pip install -e ./WebUI/command-server
      - name: Run ${{ matrix.test_file }}
        run: uv run pytest ${{ matrix.test_file }}
